### ISSUE TITLE
Add Hindi section in Ethereum in different languages

### ISSUE THREAD

**Issue by Atharv181** [FrancescoXX/free-Web3-resources#100]
**Is your feature request related to a problem? Please describe.**
Ethereum in Hindi Language

**Describe the solution you'd like**
Can add this document https://ethereum.org/hi/eth/

**Comment by mhammadsaani** [comment]
Should I?

**Comment by atharvadeosthale** [comment]
I want to work on this!

**Comment by Johnnyteck** [comment]
I'm here

**Comment by FrancescoXX** [comment]
go @Johnnyteck

**Comment by Johnnyteck** [comment]
you didn't add a label
