### ISSUE TITLE
Seperate Text roadmaps & video roadmaps

### ISSUE THREAD

**Issue by hridaya423** [FrancescoXX/free-Web3-resources#102]
**Is your feature request related to a problem? Please describe.**
Seperate Text & Video roadmaps

**Describe the solution you'd like**
There will be 2 different sections for Roadmaps (Text & Video)

**Describe alternatives you've considered**
Null

**Additional context**
Null

**Comment by hridaya423** [comment]
I already created a pr for this

**Comment by FrancescoXX** [comment]
there should be 2 sections:

### Web3 Article roadmaps

....

### Web3 Video Roadmap


Current one

![image](https://user-images.githubusercontent.com/18360871/193402098-b98d2f81-daa9-4c1b-a84d-460b5d4ce2e1.png)


Feel free to be creative on emojis :)
