### ISSUE TITLE
Add favicon to the website

### ISSUE THREAD

**Issue by Atharv181** [FrancescoXX/free-Web3-resources#104]
We can add the favicon to the website.

**Comment by FrancescoXX** [comment]
great idea, we can use a temporary one but we currently don't have a logo

**Comment by Atharv181** [comment]
![favicon](https://user-images.githubusercontent.com/73999654/193402575-89cef49b-4388-4c36-8c58-35733560494b.png)

Can we add as a favicon

**Comment by FrancescoXX** [comment]
FW3

**Comment by FrancescoXX** [comment]
[favicon_io.zip](https://github.com/FrancescoXX/free-Web3-resources/files/9689987/favicon_io.zip)
