### ISSUE TITLE
Add Defi hacks Writeups section 

### ISSUE THREAD

**Issue by baroonjha** [FrancescoXX/free-Web3-resources#113]
**Is your feature request related to a problem? Please describe.**
 Defi Hacks writeups can help people understand better.So if there will be a all hacks writeups then that will be great.So if we get all the writeups in one place then it will save our time .  [...]

**Describe the solution you'd like**
There are lots of Bug Bounty platform that publish the writeups of the hacks .

**Comment by ewainy** [comment]
Do you have examples?

**Comment by baroonjha** [comment]
Like after hacks few people write blog on it how it happened ,what the reason ,so if we just provide the link of that blog at one place ,will be good I think.

**Comment by FrancescoXX** [comment]
please provide an example link

**Comment by baroonjha** [comment]
https://pentester.land/list-of-bug-bounty-writeups.html this is the list of writeups of web2 bug .but if we can make this for  web3 bug .

**Comment by FrancescoXX** [comment]
good idea we can create a section for now

**Comment by Atharv181** [comment]
Looks great we gather such blogs and resources

**Comment by FrancescoXX** [comment]
nice idea but discussions should happen on discord
