### ISSUE TITLE
Add web3 roadmap resources in Hindi?

### ISSUE THREAD

**Issue by mhammadsaani** [FrancescoXX/free-Web3-resources#114]
**Is your feature request related to a problem? Please describe.**
The audience viewing this repository will be from Inida/Pakistan where Native language in Hindi/Urdu (almost similar). 

**Describe the solution you'd like**
Add Hindi/Urdu Web3 roadmaps

**Describe alternatives you've considered**
null

**Additional context**
null

**Comment by ewainy** [comment]
Sounds like a good idea! Do you have these resources?

**Comment by FrancescoXX** [comment]
solved by #117
