### ISSUE TITLE
Want to add a roadmap for blockchain

### ISSUE THREAD

**Issue by Heismanish** [FrancescoXX/free-Web3-resources#126]
**Is your feature request related to a problem? Please describe.**
I would like to add a blockchain roadmap.

**Describe the solution you'd like**
I would like to add a new blockchain roadmap.
[HERE](https://youtu.be/Lz3m4BI1EfY)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ewainy** [comment]
> **Is your feature request related to a problem? Please describe.** I would like to add a blockchain roadmap.
> 
> **Describe the solution you'd like** I would like to add a new blockchain roadmap. [HERE](https://youtu.be/Lz3m4BI1EfY)
> 
> **Describe alternatives you've considered** N/A
> 
> **Additional context** N/A

This resource looks good 👀 I've saved this on my own playlist to watch at a later date! I like that there is focus on frontend also. Please create a PR @Heismanish if you haven't already done so :)

**Comment by ewainy** [comment]
> I would like to add a blockchain roadmap. Please assign this to me. Thanks!

@AdityaBansal2310 What resource would you like to share? Go ahead and create a PR if this is different from Heismanish's :)

**Comment by Heismanish** [comment]
> > **Is your feature request related to a problem? Please describe.** I would like to add a blockchain roadmap.
> > **Describe the solution you'd like** I would like to add a new blockchain roadmap. [HERE](https://youtu.be/Lz3m4BI1EfY)
> > **Describe alternatives you've considered** N/A
> > **Additional context** N/A
> 
> This resource looks good eyes I've saved this on my own playlist to watch at a later date! I like that there is focus on frontend also. Please create a PR @Heismanish if you haven't already done so :)

Done with PR @ewainy  at #176 and thanks for the opportunity.

**Comment by FrancescoXX** [comment]
done!
