### ISSUE TITLE
[Documentation] Would like to add Alchemy's Road to Web3 under the Learning Platforms and YouTube Channels section.

### ISSUE THREAD

**Issue by AnshMinchekar** [FrancescoXX/free-Web3-resources#128]
**Is your feature request related to a problem? Please describe.**
I would like to add Alchemy's Road to Web3 as a learning resource under the Learning Platforms and YouTube Channels section.

**Describe the solution you'd like**
[Alchemy's Road to Web3](https://docs.alchemy.com/docs/welcome-to-the-road-to-web3)
[Alchemy's Road to Web3 YouTube Playlist](https://youtube.com/playlist?list=PLMj8NvODurfEYLsuiClgikZBGDfhwdcXF)

**Describe alternatives you've considered**

**Additional context**

**Comment by FrancescoXX** [comment]
go for it
