### ISSUE TITLE
Getting Started with Solana-Web3.js

### ISSUE THREAD

**Issue by money8203** [FrancescoXX/free-Web3-resources#133]
People should know the basics of any topic they are reading/getting into.

I want to add a link which provides topics like getting started with solana, installation guide upto solana test validator, reference api etc...

**Comment by money8203** [comment]
Added Solana Web3 learning path https://github.com/FrancescoXX/free-Web3-resources/pull/134

**Comment by money8203** [comment]
#134

**Comment by Atharv181** [comment]
As PR merged we have to close this issue.

**Comment by ewainy** [comment]
Thank you for your contribution @money8203 I will close this issue now as your PR has been merged :)
