### ISSUE TITLE
[DOCUMENTATION] Add New YouTube channel

### ISSUE THREAD

**Issue by Aakrut** [FrancescoXX/free-Web3-resources#135]
**Is your feature request related to a problem? Please describe.**
I want to add one YouTube Channel in README.md file

**Describe the solution you'd like**
Channel Link - [Chainlink](https://www.youtube.com/c/chainlink/featured)

**Describe alternatives you've considered**
null

**Additional context**
null

**Comment by ewainy** [comment]
PR has been closed so will close this issue
