### ISSUE TITLE
Add new section : Polygon Development

### ISSUE THREAD

**Issue by Rahul-Prasad-07** [FrancescoXX/free-Web3-resources#139]
### Learn to build Dapps on Polygon
**Is your feature request related to a problem? Please describe.**
- Transaction fees are too high on the Ethereum mainnet.
-  Among these Ethereum L2 scaling solutions, Polygon (formerly Matic) is the leading project. More and more Blockchain apps are being developed on Polygon, and as a Blockchain developer, it's time to get up to date.

**Describe the solution you'd like**
 _want to add Polygon development learning free content_ 

**Describe alternatives you've considered**
which content 
 -  Course Introduction
 - Polygon Ecosystem
 -  Polygon SDK

**Additional context**

**Comment by FrancescoXX** [comment]
yes open an issue to create the section
