### ISSUE TITLE
Add 'Blockchain Architecture - Understanding Monolithic & Modular Blockchains' Segment 

### ISSUE THREAD

**Issue by codewithuddy** [FrancescoXX/free-Web3-resources#143]
There is no detail whatsoever on the Modular Blockchain architecture

I will add an article on Modular and Monolithic Blockchain structures

Anyone wants to work with me on that?

**Comment by stef-codes** [comment]
Check these out! 

- I have a short article about this topic focused on Celestia: https://stefcodes.hashnode.dev/what-is-celestia-why-should-i-care
- This post is from Fuel: https://fuel-labs.ghost.io/beyond-monolithic-the-modular-blockchain-paradigm/

**Comment by ewainy** [comment]
> Check these out!
> 
> * I have a short article about this topic focused on Celestia: https://stefcodes.hashnode.dev/what-is-celestia-why-should-i-care
> * This post is from Fuel: https://fuel-labs.ghost.io/beyond-monolithic-the-modular-blockchain-paradigm/

Nice resources @stef-codes 💖

**Comment by FrancescoXX** [comment]
@codewithuddy do you still want this assigned dot you?

**Comment by stef-codes** [comment]
@FrancescoXX I can take it now and he can add more when he's ready

**Comment by codewithuddy** [comment]
@FrancescoXX ofcourse I still do want to take on the issue assigned to me, tryna fix an issue with my PC hence the delay...

@stef-codes you wanna take on it?

**Comment by codewithuddy** [comment]
Also @FrancescoXX I do not understand so well the assigned issue that I am to handle, can you explain more on what exactly I am to do?

So I can get it done as soon as I can log my github account on a public PC?

**Comment by FrancescoXX** [comment]
just add the section

**Comment by FrancescoXX** [comment]
closing this as we are migrating to docusaurus
