### ISSUE TITLE
Adding Youtube channels.

### ISSUE THREAD

**Issue by AyushJain001** [FrancescoXX/free-Web3-resources#148]
**Is your feature request related to a problem? Please describe.**
I want to add some more Youtube channels providing free guidance. 
some are:

1. Learn Web3DAO
https://youtube.com/c/LearnWeb3DAO

2. Alchemy
https://youtube.com/c/AlchemyPlatform

3. FreeCodeCamp
https://youtube.com/c/Freecodecamp

**Describe the solution you'd like**
Mentioned are some Youtube channel I request to add for more help to audience.

**Describe alternatives you've considered**

**Additional context**

I request to assign this issue to me under hacktoberfest tag

**Comment by FrancescoXX** [comment]
duplicated and freecodecamp is too generic
