### ISSUE TITLE
Style page broken

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#154]
Fix the style of the deployed page

you can find the deployed page here
https://francescoxx.github.io/free-Web3-resources/#/

![image](https://user-images.githubusercontent.com/18360871/193737263-5c909de3-fcc9-4cda-b166-85ca94efcb33.png)

**Comment by pushkaraj2007** [comment]
What is broken and what needs to be fixed?

Can you please give a bit more information about this?

**Comment by uday03meh** [comment]
Hi, I think this issue can be closed as it seems to be fixed now.

![image](https://user-images.githubusercontent.com/59679281/193948179-fb70a3bc-76a2-41f8-9911-862928120bb4.png)

**Comment by FrancescoXX** [comment]
solved
