### ISSUE TITLE
add meta tags for twitter and facebook cards

### ISSUE THREAD

**Issue by Rahulbaran** [FrancescoXX/free-Web3-resources#158]
Hi Francesco, Can I add **meta tags** for facebook & twitter cards??

**Comment by FrancescoXX** [comment]
go for it, but this is a github repository, not a website for now

**Comment by Rahulbaran** [comment]
I saw a website [link](https://francescoxx.github.io/free-Web3-resources) in repo

**Comment by FrancescoXX** [comment]
yes that's deployed directly by github. btw there is an HTML file you can modify

**Comment by Rahulbaran** [comment]
Okay, I am gonna add this soon.
