### ISSUE TITLE
Tutorials section present twice

### ISSUE THREAD

**Issue by hrsh22** [FrancescoXX/free-Web3-resources#168]
The tutorials section is present twice in the Web3 Resources.

**Comment by hrsh22** [comment]
Hey Francesco, can I merge both the tutorials sections into one?

**Comment by FrancescoXX** [comment]
they are 2 sub-sections both for solidity and vyper, we can change the title accordingly to make it more clear

e.g. 
Solidity tutorials

Vyper tutorials

**Comment by hrsh22** [comment]
Okay I can do it. Can you please assign it to me?

**Comment by FrancescoXX** [comment]
closing this. please refer to #191
