### ISSUE TITLE
Add login page

### ISSUE THREAD

**Issue by rashmirekhakumari** [FrancescoXX/free-Web3-resources#169]
**Your web pages are looking great but i think you should also add login page in right upper corner of the page which makes your web page more real. By doing this you also get data of those students who have ability to learn and build skills but they don't have proper guidance and resources so that in future you can help those students more.**

**Comment by rashmirekhakumari** [comment]
login page

**Comment by FrancescoXX** [comment]
no auth needed for now, but we can add more links to further guidance
