### ISSUE TITLE
Improving overall README section 

### ISSUE THREAD

**Issue by money8203** [FrancescoXX/free-Web3-resources#173]
The readme section is so unattractive and a bit more scary because of all the links  added there .

 It can be improved a lot more by applying some creativity. I can made the user-resource/readme interaction better and beginner friendly.

**Comment by FrancescoXX** [comment]
hi @money8203 , you are right and the goal, for now, is just to have the resources. but of course, you can work on something more appealing.

**Comment by money8203** [comment]
@FrancescoXX Sure ! will do both side by side !

**Comment by FrancescoXX** [comment]
we decided to turn this into a  Next.js project, so closing this as merged into #202 

We will discuss the style once we merge it.
