### ISSUE TITLE
Creating a Web3 website of our own

### ISSUE THREAD

**Issue by money8203** [FrancescoXX/free-Web3-resources#174]
We can create website of our own where we can provide  all the content related to Web 3 so that people don't have to waste their time clicking different links going to different websites again and again for different web3 technologies, instead we can make our own website where we will put all the resources available and present on google.

This will make people more comfortable and now instead of searching every time, visiting different web pages , wasting their time - now they will just have to go on one website and with just one click there they can find anything related to technology of their interest.

**Comment by FrancescoXX** [comment]
this is a great idea for the future! let's work on this!

**Comment by money8203** [comment]
@FrancescoXX indeed !

**Comment by money8203** [comment]
I've some frontend designs for the website i am working on, will show you when completed. 
                                     Also you can assign me a role if you wish :)

**Comment by FrancescoXX** [comment]
dependant on #202 first

**Comment by FrancescoXX** [comment]
I assigned you this one @money8203 , the website should be done using Next.js

**Comment by money8203** [comment]
Sure !

**Comment by FrancescoXX** [comment]
@money8203 , we changed idea and we want this with docusaurus, so closing this issue, you can check the other issue
