### ISSUE TITLE
Would like to add a link to this repository for the website.

### ISSUE THREAD

**Issue by AnshMinchekar** [FrancescoXX/free-Web3-resources#179]
**Is your feature request related to a problem? Please describe.**
I would like to add the repository's link on the website.

**Describe the solution you'd like**
When you click on "Free Web3 Resources 🚀" on the website, it should re-direct you to the GitHub Repository.

**Describe alternatives you've considered**

**Additional context**

**Comment by FrancescoXX** [comment]
not clear what do you mean

**Comment by AnshMinchekar** [comment]
Oh, it has already been addressed/fixed in issued #185
