### ISSUE TITLE
Remove the duplicated vietnamese sections 

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#182]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem
Remove the Vietnamese sections

![image](https://user-images.githubusercontent.com/18360871/194741766-8361c097-017a-4ab4-9962-3be06bf16267.png)

**Comment by AnshMinchekar** [comment]
Will grab this one!

**Comment by FrancescoXX** [comment]
go  for it!

**Comment by FrancescoXX** [comment]
fixed by #186
