### ISSUE TITLE
create a folder for presentation slides + move 2 files inside it

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#184]
**Is your feature request related to a problem? Please describe.**
we have slides but they are in the root folder

**Describe the solution you'd like**
Please create a folder named "presentations" and move these files there:

- https://github.com/FrancescoXX/free-Web3-resources/blob/main/SLIDES_IntroToSolidity.pdf
- https://github.com/FrancescoXX/free-Web3-resources/blob/main/intro-to-solidity.md
- https://github.com/FrancescoXX/free-Web3-resources/blob/main/HOW%20TO%20LEARN%20WEB3.pdf
- https://github.com/FrancescoXX/free-Web3-resources/blob/main/FINALHOW%20TO%20LEARN%20WEB3.pdf

**Comment by Manujdixit** [comment]
@FrancescoXX can you please add hacktoberfest label.

**Comment by vaibhav0726** [comment]
can you assign me this issue?

**Comment by FrancescoXX** [comment]
assigned to @Manujdixit

**Comment by Manujdixit** [comment]
both files are same.
by second file you may mean https://github.com/Manujdixit/free-Web3-resources/blob/main/FINALHOW%20TO%20LEARN%20WEB3.pdf

**Comment by FrancescoXX** [comment]
yes perfect

**Comment by FrancescoXX** [comment]
Updated files to add

**Comment by Manujdixit** [comment]
@FrancescoXX check the pr.

**Comment by ItzMeAditya** [comment]
@FrancescoXX can you assign this to me ?

**Comment by ewainy** [comment]
As the PR for this issue has been merged, I am closing this now.
