### ISSUE TITLE
Add a wasy to redirect from the website to the GitHub repository

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#185]
**Is your feature request related to a problem? Please describe.**
the generated website doesn't redirect to the GitHub repo

**Describe the solution you'd like**
out a GitHub icon somewhere in the file at the top to redirect to the GitHub repository

**Describe alternatives you've considered**
the icon and the positioning provided are just an example

![image](https://user-images.githubusercontent.com/18360871/194742375-5b301802-940d-4949-b0a8-6a21e8355a60.png)

**Comment by Rishav-12** [comment]
I want to work on this @FrancescoXX

**Comment by FrancescoXX** [comment]
go!
