### ISSUE TITLE
remove duplicate: Web3 roadmaps Hindi  + blog section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#187]
**Describe the bug**
We have a duplicated section to be removed

Remove "Web3 roadmaps Hindi with only one link and the blog section below"

**Screenshots**
![image](https://user-images.githubusercontent.com/18360871/194743036-a65e6125-938a-4d5e-a313-e574a02a076d.png)

**Comment by DivvSaxena** [comment]
assign me

**Comment by FrancescoXX** [comment]
go

**Comment by DivvSaxena** [comment]
e9c81a526eafde3ed7c0e2d2fde6e55688d87ea6

**Comment by DivvSaxena** [comment]
d6a6b3ded063ba095c00c568e386b15a0f608aab

**Comment by FrancescoXX** [comment]
@A-ravi assigned to you

**Comment by A-ravi** [comment]
done with #188 
removed duplicate hindi roadman and blog section

**Comment by FrancescoXX** [comment]
cool
