### ISSUE TITLE
⚒️ Restructure the Etherum Section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#191]
**Is your feature request related to a problem? Please describe.**
the Ethereum Section is not structured well

**Describe the solution you'd like**
- change the title from "Ethereum Free resources" to just Ethereum
- move "Ethereum Languages", "Solidity", "Vyper" links all below the Ethereum Section

The current situation is in the screenshot. WE want just one Ethereum Section
![image](https://user-images.githubusercontent.com/18360871/194743491-e997e301-300f-43eb-ad7b-6ec52fc08397.png)

**Comment by AnshMinchekar** [comment]
Will take this one.

**Comment by FrancescoXX** [comment]
go!

**Comment by FrancescoXX** [comment]
fixed by #200
