### ISSUE TITLE
Test vercel deployment on your fork and bring results

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#194]
please fork this repo and try to deploy it with Vercel.

Show the output

The pr should include necessary changes to have the project deployed to Vercelk if any

**Comment by AnshMinchekar** [comment]
I got this.

**Comment by AnshMinchekar** [comment]
![image](https://user-images.githubusercontent.com/99464146/194744514-82d140ba-728f-44ce-97c8-b811b8f23797.png)

**Comment by AnshMinchekar** [comment]
https://free-web3-resources.vercel.app/#/

**Comment by FrancescoXX** [comment]
Thank you so much, closing this issue
