### ISSUE TITLE
Use a single html file

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#196]
**Is your feature request related to a problem? Please describe.**
We have 2 HTML files in the repository:
- https://github.com/FrancescoXX/free-Web3-resources/blob/main/index.html
- https://github.com/FrancescoXX/free-Web3-resources/blob/main/FREE%20Web3%20Resources%20(2).html

**Describe the solution you'd like**
Having a single file for now

**Describe alternatives you've considered**

**Additional context**
please make tests and provide a solution

**Comment by Sagar191711** [comment]
please assign it to me !

**Comment by gitansh0204** [comment]
please assign it to me

**Comment by Rahulbaran** [comment]
Francesco, Why is there two html fles??

**Comment by FrancescoXX** [comment]
@Rahulbaran not sure, checks should be done locally

**Comment by FrancescoXX** [comment]
@Sagar191711 do you still want to work on this?

**Comment by bytesofbec** [comment]
Can I please get assigned this issue?

**Comment by FrancescoXX** [comment]
closing this as we will just restyle the whole website using Docusaurus
