### ISSUE TITLE
Add YouTube Channels descriptions

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#197]
**Is your feature request related to a problem? Please describe.**
Th YouTube channels section is without any description

**Describe the solution you'd like**
Please add a short description, also indicating if the channel is WEb3 focused or it has just a section or a single video on it

**Additional context**
![image](https://user-images.githubusercontent.com/18360871/194745084-60ed848e-22d5-43e6-a351-a36212b165b9.png)

**Comment by DivvSaxena** [comment]
Will Take it

**Comment by DivvSaxena** [comment]
Made A PR

**Comment by DivvSaxena** [comment]
[gh pr checkout 204](url)

**Comment by gitansh0204** [comment]
assign this to me

**Comment by DivvSaxena** [comment]
It is merged

**Comment by DivvSaxena** [comment]
#197
