### ISSUE TITLE
Remove the Table of content 

### ISSUE THREAD

**Issue by Saurabhpatil-dev** [FrancescoXX/free-Web3-resources#20]
As discussed we can remove table of contents as it is provided by Github.

**Comment by Saurabhpatil-dev** [comment]
Hi @FrancescoXX, I have created a pull request for it. Can you please chek?

**Comment by FrancescoXX** [comment]
done on https://github.com/FrancescoXX/free-Web3-resources/commit/b1a13bbe3afc9fbff87763f860b48f5954acafc7
