### ISSUE TITLE
⚡Turn the project into a Next.js project!

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#202]
**Is your feature request related to a problem? Please describe.**
Let's bring the Free Web3 Project to a new level by turning it into a Next.js project

**Describe the solution you'd like**
integrate Next.js into the project 

**please fork this repo locally and integrate the current files**

**Additional context**
Please take this issue only if you are familiar with Next.js

**Comment by FrancescoXX** [comment]
after we deploy all the info in the NExt.js project, we will call this version 1.0.0

**Comment by FrancescoXX** [comment]
not required to have the same style or dark/light mode

**Comment by Wra8th** [comment]
Is it supposed to be developed from scratch or have you provided some code to work on?

**Comment by money8203** [comment]
@Wra8th you can work on it from scratch and suggest your ideas !

**Comment by FrancescoXX** [comment]
@Yuvrajchandra this looks interesting, but can we add more functionalities later?
