### ISSUE TITLE
Add Description on Open Source projects 1/2

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#205]
**Is your feature request related to a problem? Please describe.**
Open Source projects have no description

**Describe the solution you'd like**
Please add a description to the first half of the Open source Projects

from A to "Holochain"

![image](https://user-images.githubusercontent.com/18360871/194747402-117ed172-6a6f-44e9-8ac6-ca6e003770f1.png)

**Comment by DivvSaxena** [comment]
assign it to me

**Comment by gitansh0204** [comment]
assign it to me

**Comment by DivvSaxena** [comment]
Made the PR

**Comment by FrancescoXX** [comment]
fixed by #210
