### ISSUE TITLE
Add Description on Open Source projects 2/2

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#206]
Is your feature request related to a problem? Please describe.
Open Source projects have no description

Describe the solution you'd like
Please add a description to the second half of the Open source Projects

from Hyperledger to the ends

![image](https://user-images.githubusercontent.com/18360871/194747521-9117465a-846e-4d32-bf2a-1fa79623e407.png)

**Comment by DivvSaxena** [comment]
Not greedy ......

**Comment by gitansh0204** [comment]
assign it to me
