### ISSUE TITLE
Add missing Web3 roadmaps (Video) have no description

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#208]
Is your feature request related to a problem? Please describe.
Some Web3 roadmaps have no description

Describe the solution you'd like
Please add the description to the missing ones

![image](https://user-images.githubusercontent.com/18360871/194747714-78459653-e549-4745-ad42-a672f4436c9f.png)

**Comment by vaibhav0726** [comment]
assign it to me

**Comment by FrancescoXX** [comment]
fixed by #209

**Comment by vaibhav0726** [comment]
you didn't add hacktoberfest-accepted to #209 pr @FrancescoXX
