### ISSUE TITLE
Different blockchain/ web3 coin's whitepaper

### ISSUE THREAD

**Issue by jsvigneshkanna** [FrancescoXX/free-Web3-resources#211]
**Is your feature request related to a problem? Please describe.**
This is a new section feature

**Describe the solution you'd like**
We can add new section called blockchain whitepaper which have official docs/ whitepapers from different coin orgs

**Additional context**
This would Increase the reading of official docs from orgs

**Comment by FrancescoXX** [comment]
I like this idea, but I want the section being divided by Blockchain.

We can add issues for missing whitepapers in relative Blockchain sections
