### ISSUE TITLE
Wrong placement of github logo

### ISSUE THREAD

**Issue by vaibhav0726** [FrancescoXX/free-Web3-resources#212]
why github logo in the left list?
![image](https://user-images.githubusercontent.com/89084390/194749419-d364f70e-9fcc-4d06-bbda-7fc01c47507f.png)

**Comment by FrancescoXX** [comment]
it's to redirect to the GitHub repository from the website. IT can be improved but we implemented the functionality

**Comment by vaibhav0726** [comment]
so it is ok 
![image](https://user-images.githubusercontent.com/89084390/194749858-01cd1f24-0ac5-4f73-b701-1eba7dbf94b8.png)
