### ISSUE TITLE
Move the languages in the "Ethereum in different languages section" 

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#213]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
move the Portuguese to Vietnamese section under "Ethereum in different languages"

![image](https://user-images.githubusercontent.com/18360871/194750190-da66a149-ef9a-4c3d-96e0-66b81b56fa72.png)

![image](https://user-images.githubusercontent.com/18360871/194750065-60b38dac-ee93-4ea1-8f35-cba717c53f1e.png)

**alternatives**
also, remove the subtitle and put them just in one line (optional)

**Comment by DivvSaxena** [comment]
will take it

**Comment by FrancescoXX** [comment]
not valid for hacktoberfest, but still valid fo the project!

**Comment by DivvSaxena** [comment]
Made the PR #215
