### ISSUE TITLE
Index for ReadMe.md

### ISSUE THREAD

**Issue by MadhuSaini22** [FrancescoXX/free-Web3-resources#237]
**Is your feature request related to a problem? Please describe.**
While looking on the Readme file, I have to scroll a lot, which is bad user experience.

**Describe the solution you'd like**
We can make an index for whole Readme file so that user can directly look on to each section of Readme.

@FrancescoXX , kindly assign this task to me, want to work on this with Hacktoberfest2022 label

**Comment by ewainy** [comment]
> **Is your feature request related to a problem? Please describe.** While looking on the Readme file, I have to scroll a lot, which is bad user experience.
> 
> **Describe the solution you'd like** We can make an index for whole Readme file so that user can directly look on to each section of Readme.
> 
> @FrancescoXX , kindly assign this task to me, want to work on this with Hacktoberfest2022 label

Is this like a table of contents? I think this would look really nice if so 😊

**Comment by MadhuSaini22** [comment]
> > **Is your feature request related to a problem? Please describe.** While looking on the Readme file, I have to scroll a lot, which is bad user experience.
> > **Describe the solution you'd like** We can make an index for whole Readme file so that user can directly look on to each section of Readme.
> > @FrancescoXX , kindly assign this task to me, want to work on this with Hacktoberfest2022 label
> 
> @MadhuSaini22 Is this like a table of contents? I think this would look really nice if so 😊

Yes, it's kind of table of contents :)
Do assign this task to me

**Comment by FrancescoXX** [comment]
hi @MadhuSaini22 , assigned, thanks!
