### ISSUE TITLE
Discord Link for 4C community 

### ISSUE THREAD

**Issue by Saurabhpatil-dev** [FrancescoXX/free-Web3-resources#24]
Hi all, as we have a discord community, we can add its link in readme to help more people join community.

**Comment by Saurabhpatil-dev** [comment]
@Pradumnasaraf can you add good first issue label to this issue ?

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf can you add good first issue label to this issue ?

Hey! Saurabh I am not a maintainer of this repo, Francesco can only add labels.
