### ISSUE TITLE
add a polygon section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#243]
### Is your feature request related to a problem? Please describe.

we are missing a "Polygon" with content focused on learning Polygon blockchain

### Describe the solution you'd like

 add a section with the title Polygon and using # before it

### Describe alternatives you've considered

add one relevant resource to get the hacktoberfest contribution

**Comment by DivvSaxena** [comment]
Assign it to  me

**Comment by DivvSaxena** [comment]
#250

**Comment by FrancescoXX** [comment]
closed by #250
