### ISSUE TITLE
Adding blog

### ISSUE THREAD

**Issue by Atharv181** [FrancescoXX/free-Web3-resources#249]
### 📚 Documentation

I have written 3 blogs on blockchain if you think that it is helpful then we can add those in resources.

Please have a look on these blogs.
`https://atharvbobade.hashnode.dev/blockchain-concepts-used-to-createsecure-blockchain`
`https://atharvbobade.hashnode.dev/blockchain-evolution-of-web-30-and-some-concepts-of-blockchain`
`https://atharvbobade.hashnode.dev/working-of-blockchain-and-challenges`

**Comment by FrancescoXX** [comment]
this should not be a self-promo project

**Comment by Atharv181** [comment]
Yes definitely but thought this would be helpful
No issues 👍
