### ISSUE TITLE
Add descriptions on Solana Articles

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#251]
### Is your feature request related to a problem? Please describe.

Solana resources don't have a short description

![image](https://user-images.githubusercontent.com/18360871/195160624-2db3aa0a-1a46-4e97-a4cb-103d0093af43.png)

### Describe the solution you'd like

add a concise description on Solana articles using Markdown

**Comment by DivvSaxena** [comment]
assign it to me
