### ISSUE TITLE
Footer should be there on website

### ISSUE THREAD

**Issue by MadhuSaini22** [FrancescoXX/free-Web3-resources#254]
### Is your feature request related to a problem? Please describe.

In this website repo, we don't have footer.
Footer completes the whole website, so it's nice to have footer on our website.

### Describe the solution you'd like

I think, we can a footer for our website.

### Describe alternatives you've considered

@FrancescoXX , would love to work on this task, kindly assign this task to me.

**Comment by Adharen** [comment]
Hii please assign me this issues

**Comment by FrancescoXX** [comment]
please refer to #274 . it will contain a footer

**Comment by FrancescoXX** [comment]
go for it @MadhuSaini22
