### ISSUE TITLE
Add Job Boards

### ISSUE THREAD

**Issue by Rahul-Prasad-07** [FrancescoXX/free-Web3-resources#261]
### Is your feature request related to a problem? Please describe.

I want add job bords that helps developers to find jobs

## Job Boards
- I want to add job bords 
   - [Angel.co](https://angel.co/web3)
   - [BlockAce](https://blockace.io/)
   - [NoDesk](https://nodesk.co/remote-jobs/blockchain-cryptocurrency-jobs/)
   - [CryptoDevHub](https://cryptodevhub.io/blockchain-developer-jobs)
   - [Cryptocurrencyjobs](https://cryptocurrencyjobs.co/)
   - [Cryptojoblist](https://cryptojobslist.com/)
   - [Blockew](https://blockew.com/)
   - [BlockAce](https://blockace.io/)
   - [Ethlance](https://ethlance.com/)
   - [Indeed](https://www.indeed.com/jobs?q=blockchain%20developer)
   - [Glassdoor](https://www.indeed.com/jobs?q=blockchain%20developer)
   - [Arc.dev](https://arc.dev/remote-jobs?categories=Blockchain)
   - [Web3.career](https://web3.career/)
   - [UseWeb3](https://www.useweb3.xyz/jobs)
   - [Remote3](https://remote3.co/web3-jobs)

**Comment by FrancescoXX** [comment]
this website is focused on resources to learn for now, but let's keep an eye on this

**Comment by Rahul-Prasad-07** [comment]
Hey @FrancescoXX  

Do i have to add job boards ? Or Modified my pr and find learning resources from them ?

**Comment by FrancescoXX** [comment]
closing this as we are just focused on the learning process for now, not finding a job
