### ISSUE TITLE
Too many back to top button

### ISSUE THREAD

**Issue by Eugene44-hub** [FrancescoXX/free-Web3-resources#269]
### Is your feature request related to a problem? Please describe.

Almost each sections contains a back to top button

### Describe the solution you'd like

Creating a fixed 'back to top' button on the webpage would be nice instead of having it in all sections

### Describe alternatives you've considered

The back to top button should be shown when user's scroll away from the top of the webpage and can be clicked to take the the user back at the top of the page

**Comment by Eugene44-hub** [comment]
If this is considered and approved can you kindly assign to me.

**Comment by FrancescoXX** [comment]
done

**Comment by FrancescoXX** [comment]
we can close this one as we will do this #274
