### ISSUE TITLE
⚡Turn the project into a Docusaurus project!

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#274]
### Is your feature request related to a problem? Please describe.

now the project is mainly a .md file. 

We want to bring this to the Next level, by using docusaurus.

For now we just need an empty project on a branch called "docusaurus"

you can start here
https://docusaurus.io/docs

### Describe the solution you'd like

create an empty docusaurus project inside the repository and test it

it should be on a branch called "docusaurus"

**Comment by Adi-Abhishek** [comment]
Hey! I want to work on this but don't know how to start?
Can you  guide me for these?

**Comment by ardasevinc** [comment]
Hey Francesco! I'm currently working on this.

**Comment by FrancescoXX** [comment]
hey @ardasevinc , I can make you a maintainer of the project and see if that works.

**Comment by ardasevinc** [comment]
> hey @ardasevinc , I can make you a maintainer of the project and see if that works.

Sure! That'd be awesome.

**Comment by FrancescoXX** [comment]
done!
