### ISSUE TITLE
[FEATURE] README.md

### ISSUE THREAD

**Issue by ShorunTech** [FrancescoXX/free-Web3-resources#277]
### Is your feature request related to a problem? Please describe.

In the readme.md section the index part the list of content there some list are broken not linking to the full details of the content.

![Screenshot (220)](https://user-images.githubusercontent.com/61280687/196112031-aa9bc6bf-f7f9-4e54-8bee-4ad76b3ace22.png)
![Screenshot (222)](https://user-images.githubusercontent.com/61280687/196112060-d2988ed0-b124-4091-af77-5834a03d719d.png)

### Describe the solution you'd like

By Clicking on each link should navigate down to the full content.

![Screenshot (223)](https://user-images.githubusercontent.com/61280687/196112954-6f7ba2c9-1f54-4186-829d-9622de9256dc.png)

![Screenshot (225)](https://user-images.githubusercontent.com/61280687/196112894-13228825-d9d3-444c-b8e4-f055edf3873f.png)

**Comment by ShorunTech** [comment]
I can work on this if assign to me.

**Comment by FrancescoXX** [comment]
go for it @ShorunTech

**Comment by ShorunTech** [comment]
Thank you @FrancescoXX

**Comment by FrancescoXX** [comment]
closing this as we are migrating to docusaurus
