### ISSUE TITLE
Update Contributors guidelines

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#29]
Suggest Contributors guidelines

**Comment by krshdev** [comment]
Can I be assigned to this? Thank you

**Comment by FrancescoXX** [comment]
done!

**Comment by krshkodes** [comment]
Hey! I am kinda occupied with a quite of bit of work, so I hope you don't mind if I submit a PR by the weekend! :D

**Comment by ewainy** [comment]
I don't think there is any rush Krish, so don't worry too much! I am the same, lots of work on! Hope to catch up with you at the weekend. Take care :)

**Comment by ewainy** [comment]
@krshkodes can this issue be closed? Your contribution guide is amazing :)

**Comment by krshkodes** [comment]
Yes! Absolutely
