### ISSUE TITLE
FreeCodeCamp course

### ISSUE THREAD

**Issue by ThomasCode92** [FrancescoXX/free-Web3-resources#292]
### Is your feature request related to a problem? Please describe.

Can I add a FreeCodeCamp resource to the README.md file.

### Describe the solution you'd like

I would like to add this YouTube video: https://www.youtube.com/watch?v=gyMwXuJrbJQ.
It's a 32 hour course about Blockchain, Solidity, and Full Stack Web3 Development with JavaScript.

### Additional context

This will be me first PR in an Open Source repo. So any help woudl be appreciated.

**Comment by FrancescoXX** [comment]
we are not focused on a single platform, but rather on tutorials on different blockchains. that video is already in the available resources
