### ISSUE TITLE
Center the polygon image

### ISSUE THREAD

**Issue by Atharv181** [FrancescoXX/free-Web3-resources#299]
### Have you checked if the same issue has already been raised ?

- [X] I have checked and didn't find similar issue

### Describe the bug

Can we align image of polygon in center because all other images are centered except polygon one.

### Steps to reproduce

1. Go to Readme'
2. Scroll down to 'Polygon Section'
3. See error

### Expected behavior

Polygon image will be center allign

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by satyamkale27** [comment]
I want to work on this issue please assign to me.

**Comment by FrancescoXX** [comment]
done
