### ISSUE TITLE
Fix minor typo in Readme markdown code

### ISSUE THREAD

**Issue by AshwanthramKL** [FrancescoXX/free-Web3-resources#305]
### 📚 Documentation

Under the subsection Youtube channels, the link to Francesco's channel appears at the same line as that of the previous channel.
Hence it is usually overlooked as people don't usually read till the end of the line.

### Add relevant screenshot or video (if any)

![before](https://user-images.githubusercontent.com/71945723/200155810-33bda879-c8ee-4ed3-ad38-56267757b99f.jpg)

### Additional context

Accidentally created a PR( #304 ) before opening an issue.
Hope it will still be considered.

**Comment by FrancescoXX** [comment]
done
