### ISSUE TITLE
Add yarn related entries to gitignore

### ISSUE THREAD

**Issue by ardasevinc** [FrancescoXX/free-Web3-resources#309]
## The problem

@FrancescoXX Switched to yarn for docusaurus'. Now we have these files that will be committed when someone runs `yarn` or `yarn install` in the project root
![yarn files](https://user-images.githubusercontent.com/42278637/200183171-32163351-dd23-4d76-8416-ba3505dd7db3.png)

In my opinion, `.yarn/` and `.yarnrc.yml` shouldn't be committed. `yarn.lock` however, should be committed. It ensures that all the developers on this project install the same package. See [a post by yarn themselves](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/)

**Comment by FrancescoXX** [comment]
please handle this on the .gitignore file
