### ISSUE TITLE
change the Twitter handle to the 4c community one

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#311]
### Is your feature request related to a problem? Please describe.

change the current Twitter handle redirection to the 4c Twitter account:

https://twitter.com/4ccommunityhq

you should update the docusaurus.config.js file

line 105
![image](https://user-images.githubusercontent.com/18360871/200184123-0785590b-1fc8-4dfd-a914-390e1b1a5383.png)

![image](https://user-images.githubusercontent.com/18360871/200184088-9f2cbe67-e6df-4ca5-b8b8-c613962615d8.png)

### Describe the solution you'd like

clicking on the Twitter link redirects you to https://twitter.com/4ccommunityhq

**Comment by RakeshSangem** [comment]
I want to work on it.

**Comment by ardasevinc** [comment]
> I want to work on it.

Please go ahead, I'll assign you

**Comment by RakeshSangem** [comment]
> > I want to work on it.
> 
> Please go ahead, I'll assign you

Thank you, @ardasevinc

**Comment by ardasevinc** [comment]
> > > I want to work on it.
> > 
> > 
> > Please go ahead, I'll assign you
> 
> Thank you, @ardasevinc

Good luck! Keep us posted
