### ISSUE TITLE
Add discord link in the footer

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#313]
### Is your feature request related to a problem? Please describe.

please update the docusaurus.config.js file to redicrect to the 4c community Discord server

![image](https://user-images.githubusercontent.com/18360871/200184352-161ecc2a-c75c-48df-9041-dadbb15cfc4f.png)

link to use: https://discord.com/invite/JZ2btyTfzQ

### Describe the solution you'd like

clicking on the discord link in the footer you should be redirected to the discord server

**Comment by andrewkykoo** [comment]
Hi @FrancescoXX @ardasevinc, I would like to help with this issue. Thanks.

**Comment by ardasevinc** [comment]
resolved with #318
