### ISSUE TITLE
Algolia Integration

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#314]
### Is your feature request related to a problem? Please describe.

integrate Algolia search functionalioty in the current docusaurus project

### Describe the solution you'd like

Algolia should be enabled and visible on the top-right.

Something like this:

![image](https://user-images.githubusercontent.com/18360871/200184467-003f7e92-6d26-48b4-bcec-58d15f845412.png)

**Comment by ardasevinc** [comment]
I will take this, I have already determined the first steps to integrate algolia docsearch.

According to docusarus' [search docs](https://docusaurus.io/docs/search) to use Algolia DocSearch we must apply to the DocSearch program [here](https://docsearch.algolia.com/apply/). 

[The checklist](https://docsearch.algolia.com/docs/who-can-apply/) for applying says that we must already have the content before application as they will not validate our request otherwise.

![screenshot from algolia docsearch application checklist](https://user-images.githubusercontent.com/42278637/200185284-71adace1-5135-476b-919c-349aa9210f7b.png)
 
@FrancescoXX the owner needs to apply to this program

**Comment by FrancescoXX** [comment]
yes I think this is on me

**Comment by tobySolutions** [comment]
Is the Algolia integration something that will require extra configurations @FrancescoXX?

**Comment by FrancescoXX** [comment]
I sent  the request, only I can do this. work in progress, let's update in some weeks as they are usually slow

**Comment by tobySolutions** [comment]
> I sent the request, only I can do this. work in progress, let's update in some weeks as they are usually slow

Awesome @FrancescoXX. No problemo!

**Comment by ardasevinc** [comment]
> Is the Algolia integration something that will require extra configurations @FrancescoXX?

Well if we are accepted they will index our website for free. That's Francesco had to apply.

If you look at the checklist I sent above, they want a production ready website (usually a documentation or blog as they mentioned). I think we should've designed the landing page of freeweb3resources.com before applying. It still has some placeholders. I actually wanted to remove the placeholders and create at least a custom landing page but I never got to start it...

**Comment by tobySolutions** [comment]
> > Is the Algolia integration something that will require extra configurations @FrancescoXX?
> 
> Well if we are accepted they will index our website for free. That's Francesco had to apply.
> 
> If you look at the checklist I sent above, they want a production ready website (usually a documentation or blog as they mentioned). I think we should've designed the landing page of freeweb3resources.com before applying. It still has some placeholders. I actually wanted to remove the placeholders and create at least a custom landing page but I never got to start it... 

No problem Arda, all will be handled.

**Comment by tobySolutions** [comment]
We're in this together.

**Comment by tobySolutions** [comment]
How's this going @FrancescoXX?

**Comment by tobySolutions** [comment]
@FrancescoXX??

**Comment by tobySolutions** [comment]
Any updates on this @ardasevinc, @FrancescoXX??

**Comment by tobySolutions** [comment]
Thanks for the response @ardasevinc!!

**Comment by tobySolutions** [comment]
Any updates @FrancescoXX??

**Comment by tobySolutions** [comment]
Can I close this @FrancescoXX?

**Comment by FrancescoXX** [comment]
why close it? it just needs time and I am working on the integration

**Comment by tobySolutions** [comment]
It's done now, right @FrancescoXX.
