### ISSUE TITLE
Alphabetical order

### ISSUE THREAD

**Issue by vikasganiga05** [FrancescoXX/free-Web3-resources#32]
Alphabetize each section's name and the list of items inside each section. This makes it easier for viewers to find what they are looking for.

**Comment by FrancescoXX** [comment]
That makes sense I also thought about this

**Comment by ewainy** [comment]
It's a good idea for sure 😊💡

**Comment by vikasganiga05** [comment]
Thank You :pray:

**Comment by krshdev** [comment]
This is a awesome idea, I think we should add this to the contributing guide #29

**Comment by FrancescoXX** [comment]
good idea!

**Comment by ithiel883** [comment]
can i be assigned this issue?

**Comment by ewainy** [comment]
Hi @ithiel883 thank you for this, we appreciate the help! I have assigned this issue to you now.

**Comment by ithiel883** [comment]
okay, i will work on it now

**Comment by Dheer3999** [comment]
Good~~~~

**Comment by mkubdev** [comment]
Hi, i can work on this right now, can i be assigned ?

**Comment by ewainy** [comment]
> Hi, i can work on this, can i be assigned ? ⚡

@mkubdev please check with @ithiel883 
@ithiel883 can you provide an update of where this issue is upto :)

**Comment by mkubdev** [comment]
@ewainy Alright! Let's wait for @ithiel883 update :)

**Comment by mkubdev** [comment]
Hi, any news from @ithiel883 ?

**Comment by ewainy** [comment]
> Oops... i mentioned the issue from my fork but I do not know that it'll reference here sorry. Any news from @ithiel883 ?

@mkubdev I didn't hear anything, did you? 👀

I'm going to reassign this as we have left it enough time, so I think we have been more than fair.

**Comment by mkubdev** [comment]
Hi @ewainy 👋🏻 No, no news!
Thanks a lot, I'll open a PR asap. Thanks for assigning me. 💡

**Comment by ewainy** [comment]
Happy with the PR by @mkubdev going to close this issue, we can create additional issues which match section worked in the future.
