### ISSUE TITLE
Adding one more amazing platform containing free resources

### ISSUE THREAD

**Issue by ankasaw99** [FrancescoXX/free-Web3-resources#327]
### Is your feature request related to a problem? Please describe.

Adding a learning platform to list

### Describe the solution you'd like

Thank you **Francesco** and the **contributors** for collecting wonderful resources for web3 enthusiasts.
I would like to suggest one more platform to add to this amazing list.

Platform Name : **DApp World**
Website: https://dapp-world.com

Description : One stop platform for web3 developers, Everything you need to Upskill yourself in the web3 domain. 
You can learn through free certification Courses, Tutorials, Guides, Articles, Quizzes Assessments, and much more.

Let me know if I am missing any protocol for the submission of the request.

Thank You

**Comment by tobySolutions** [comment]
Do you want to add this @ankasaw99

**Comment by ankasaw99** [comment]
Yes please !

**Comment by ankasaw99** [comment]
Yes Please @tobySolutions

**Comment by tobySolutions** [comment]
Awesome @ankasaw99!!!!

**Comment by tobySolutions** [comment]
Hey @ankasaw99, there's the direct edit available in the docs now, you can use that to raise a PR. You don't have to build the project locally
