### ISSUE TITLE
Add a Youtube Video

### ISSUE THREAD

**Issue by Sriparno08** [FrancescoXX/free-Web3-resources#328]
### 📚 Documentation

I have found a great resource that will help people become a Blockchain developer!

Title: How to Become a Blockchain Developer in 2023 (Roadmap)
Platform: Youtube
Link: https://www.youtube.com/watch?v=zglv3lCchSo

**Comment by Sriparno08** [comment]
I would like to add this resource, @FrancescoXX!

**Comment by tobySolutions** [comment]
Sure thing @Sriparno08, feel free to raise a PR!

**Comment by tobySolutions** [comment]
I can assign you to this if you want.

**Comment by Sriparno08** [comment]
Yeah, sure! 👍

**Comment by tobySolutions** [comment]
I'll be expecting your PR.

**Comment by Sriparno08** [comment]
Sure thing, @tobySolutions 👍

**Comment by tobySolutions** [comment]
Check my comment on your PR @Sriparno08!

**Comment by Sriparno08** [comment]
Made a PR, maintainers! Have a look!
