### ISSUE TITLE
Duplicated release.yml

### ISSUE THREAD

**Issue by victoriacheng15** [FrancescoXX/free-Web3-resources#340]
### Have you checked if the same issue has already been raised ?

- [X] I have checked and didn't find similar issue

### Describe the bug

There are 2 release.yml files, one is in `.github` folder and another one is in the `workflows` folder

### Expected behavior

The release.yml in `.github` folder should be deleted.

### Desktop

N/A

### Smartphones

N/A

**Comment by tobySolutions** [comment]
Yeah, I just noticed that as well. Do you want to work on this @victoriacheng15?

**Comment by victoriacheng15** [comment]
> Yeah, I just noticed that as well. Do you want to work on this @victoriacheng15?

Sure!

**Comment by tobySolutions** [comment]
Awesome!! It's all yours!
