### ISSUE TITLE
A beautiful scroll bar of same color palette

### ISSUE THREAD

**Issue by Agrim-Sharma174** [FrancescoXX/free-Web3-resources#344]
### Is your feature request related to a problem? Please describe.

It looks very good to me if a website has a scroll bar of color similar to the website color palette

### Describe the solution you'd like

I will add a custom scroll bar of the #2E8555 color, similar to the color of highlighted words.

**Comment by Agrim-Sharma174** [comment]
How it will look like:
![image](https://user-images.githubusercontent.com/97873694/210211239-60156144-e155-49d4-8408-a35e18050b26.png)

How it will look like, on hover:
![image](https://user-images.githubusercontent.com/97873694/210211337-e13906e9-0dce-4fe8-9408-69502586afa9.png)

**Comment by tobySolutions** [comment]
Awesome issue!! Do you want to work on this @Agrim-Sharma174?

**Comment by Agrim-Sharma174** [comment]
Yes, I want to do this!
Just raising the PR.
