### ISSUE TITLE
Remove Unnecessary Pages: "Tutorial Basics" and "Tutorial Extras"

### ISSUE THREAD

**Issue by tobySolutions** [FrancescoXX/free-Web3-resources#345]
### Is your feature request related to a problem? Please describe.

The site needs to do away with the default Docusaurus pages and begin to adopt and and add pages that are related to the purpose of the site.

Pages like "Tutorial Basics", "Tutorial Extras" and "Blogs" are some of those pages.

### Describe the solution you'd like

Complete removal of the pages including the routes to them. If in the future we need information about something, we can refer to https://docs.daily.dev/ or https://docusaurus.io/ for information on how to do certain tasks.

![Screenshot from 2023-01-02 11-08-41](https://user-images.githubusercontent.com/96334363/210218246-d989d64c-5a5f-4958-b56a-f2b73d40ef41.png)

**Comment by devvsakib** [comment]
@tobySolutions assign me, i have to remove "Tutorial Basics", "Tutorial Extras" and "Blogs" pages right?
