### ISSUE TITLE
Change Call To Action To Information That Matters To The Project

### ISSUE THREAD

**Issue by tobySolutions** [FrancescoXX/free-Web3-resources#346]
### Is your feature request related to a problem? Please describe.

The Call To Action of a site needs to reflect what the site is about with relevant images at times to further illustrate. We need to change the Call to action on this site to stuff related to Free Web 3 Resources.

![Screenshot from 2023-01-02 11-18-54](https://user-images.githubusercontent.com/96334363/210218719-59b0b1d5-2fc4-4a23-aa67-14b8989d2fe3.png)

### Describe the solution you'd like

A total edit of the call to action to match relevant information about the Free web3 resources and the 4C community behind the project.

![Screenshot from 2023-01-02 11-18-54](https://user-images.githubusercontent.com/96334363/210218837-5e750c7f-0d39-4900-a628-1e007930a340.png)

**Comment by FrancescoXX** [comment]
I agree. this is just a Docusaurus placeholder. 

The first step would be to remove all the docusaurus references and add a simple front page

we can take inspiration from https://docs.daily.dev/

**Comment by tobySolutions** [comment]
> I agree. this is just a Docusaurus placeholder.
> 
> The first step would be to remove all the docusaurus references and add a simple front page
> 
> we can take inspiration from https://docs.daily.dev/

Yes, we can take inspiration from the Daily dev docs for sure!

**Comment by tobySolutions** [comment]
Hey @FrancescoXX, you could help by providing the right information to put on the landing page. Stuff about Free Web 3 Resources.

**Comment by ardasevinc** [comment]
Also, can we get any design help for the landing page? Maybe a cool logo at least haha

**Comment by tobySolutions** [comment]
Fixed by #362
