### ISSUE TITLE
Documentation should explain how to contribute to the Docusaurus Code

### ISSUE THREAD

**Issue by tobySolutions** [FrancescoXX/free-Web3-resources#354]
### 📚 Documentation

The repository has no guideline of any sort to guide first-timers that have no web 3 resources to contribute but want to contribute to the code.

We need Guideline Documentation to assist users to be able to contribute to the code and assist in breaking down the Docusaurus Framework for first-timers.

**Comment by FrancescoXX** [comment]
we can tell people they can use the edit button on pages. that's the best way to contribute for the resources

for the project itself, yes we will create sort of guidelines, you cna assign this to me

**Comment by tobySolutions** [comment]
Awesome @FrancescoXX!! Thanks

**Comment by tobySolutions** [comment]
You still working on this @FrancescoXX?
