### ISSUE TITLE
[Docs]: Improved the structure of the instructions

### ISSUE THREAD

**Issue by the-amazing-atharva** [FrancescoXX/free-Web3-resources#369]
### Description

Re-arranged the written instructions for Contributing and Contributing Resources from a paragraph form to a more appealing unordered list by using markdown synatx

(I would like to be assigned to work on the update)

Screenshots added below :

## Before :

![Screenshot before 4c](https://user-images.githubusercontent.com/121221252/212966426-4882dce0-fe99-4a6a-b662-cfd9969631ab.png)

## After : 
![Screenshot after 4c](https://user-images.githubusercontent.com/121221252/212966419-9517a92e-2edc-41e6-95b7-f114f10157d4.png)

(do let me know if the update is not required)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by tobySolutions** [comment]
It looks awesome @the-amazing-atharva!!

**Comment by the-amazing-atharva** [comment]
Thanks for assigning me here too toby

**Comment by the-amazing-atharva** [comment]
Thanks once gain Toby!
