### ISSUE TITLE
####YouTube####

### ISSUE THREAD

**Issue by JayrajSingh65** [FrancescoXX/free-Web3-resources#37]
< --- I found problem that there is no direct link open in YouTube --->

**solution I would like**
A clear and concise description of what I want or users 

**To make better experience for people provide direct link open in  YouTube which may help them to explore that channel so that they can find their relative content etc. **

**Comment by JayrajSingh65** [comment]
What you guys think about this?  🤔

**Comment by tawseefnabi** [comment]
youtube tutorials related web3 is good option. there are many channels which provide ample knowledge about it

**Comment by FrancescoXX** [comment]
Hi @JayrajSingh65, can you please explain what do you mean? adding youtube videos/channels about Web3?

**Comment by JayrajSingh65** [comment]
There should be link for YouTube channels  of web3 and crypto so users can easily explore youTube content related to web3 

Give link of some following YouTube channels

1. Whiteboard crypto
2. Dapp university 
Etc.
[YouTube ](https://youtu.be/oPIupbsVimc)

**Comment by JayrajSingh65** [comment]
There should be link for YouTube channels  of web3 and crypto so users can easily explore youTube content related to web3 

Give link of some following YouTube channels

1. Whiteboard crypto
2. Dapp university 
Etc.
[YouTube ](https://youtu.be/oPIupbsVimc)


Add links of YouTube channels in  Readme.md

**Comment by FrancescoXX** [comment]
done by 48c7aee6cc1efd277cedc811bfbfce5295b42071
