### ISSUE TITLE
[Docs]: Better Readme

### ISSUE THREAD

**Issue by krshkun** [FrancescoXX/free-Web3-resources#372]
### Description

One of our projects `4C-site` has a very nice readme that I'm a big fan of, can we replicate that here?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by tobySolutions** [comment]
This is a very good one @krshkun. Would you like to work on this??

**Comment by krshkun** [comment]
Ha, I'm not having really that much time to write a full Readme since my exams are arriving and I keep on taking challenges 😂

**Comment by tobySolutions** [comment]
@money8203 has taken the issue. Don't worry about it @krshkun.

**Comment by tobySolutions** [comment]
For whoever wants to copy the 4c site readme, here is the link:
https://github.com/FrancescoXX/4c-site/blob/main/README.md

**Comment by money8203** [comment]
I'm taking it!!

**Comment by tobySolutions** [comment]
Awesome!!!

**Comment by tobySolutions** [comment]
I just assigned you @money8203. I'll be expecting your PR.

**Comment by money8203** [comment]
> For whoever wants to copy the 4c site readme, here is the link: https://github.com/FrancescoXX/4c-site/blob/main/README.md

I've to update this one or the one present currently ?

**Comment by tobySolutions** [comment]
> > For whoever wants to copy the 4c site readme, here is the link: https://github.com/FrancescoXX/4c-site/blob/main/README.md
> 
> I've to update this one or the one present currently ?

You can follow this to serve as a template for the new one you'll be adding to the site

**Comment by tobySolutions** [comment]
@money8203.

**Comment by tobySolutions** [comment]
You still working on this @money8203?

**Comment by money8203** [comment]
Yepp

**Comment by tobySolutions** [comment]
Awesome! Great job #378
