### ISSUE TITLE
[Docs]: Pull request template

### ISSUE THREAD

**Issue by krshkun** [FrancescoXX/free-Web3-resources#373]
### Description

We do not have a pull request template, maybe we can add that?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by tobySolutions** [comment]
Sure!! We do need a template. Wanna work on this @krshkun??

**Comment by money8203** [comment]
What happens to this template ?

https://github.com/FrancescoXX/free-Web3-resources/blob/main/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md

**Comment by tobySolutions** [comment]
Great job @money8203!!!
