### ISSUE TITLE
[Feat]: Change Site's Lightmode Color Scheme to match 4C site theme

### ISSUE THREAD

**Issue by tobySolutions** [FrancescoXX/free-Web3-resources#380]
### Description

The freeweb3resources.com needs to exhibit the uniqueness of a project that is managed by the Cool Community Of Content Creators and how best to do that, but by changing the color scheme to match https://www.4c.rocks/.

### Solution

The site's light-mode color scheme can be changed to match the https://www.4c.rocks/ color scheme in the global CSS.

### Anything else?

Check out https://www.github.com/FrancescoXX/4c-site.

![Screenshot from 2023-01-30 10-42-04](https://user-images.githubusercontent.com/96334363/215442056-7b35a326-e75a-407a-b213-d672fb3e3802.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by FrancescoXX** [comment]
yes we can work on this and we can use docusaurus to handle this color scheme 

you can use this
https://github.com/FrancescoXX/4c-site/tree/main/docs/theme

I think the first step is to remove all the dinosaurus and make it look similar to 
https://docs.daily.dev/

not the same suing the icons, it's just to have an idea of the alyout

I am not a frontend engineer but if noone cna work on this I will take care of this.

![image](https://user-images.githubusercontent.com/18360871/215870851-e0b81950-7edc-4435-911e-982761c62ec1.png)

**Comment by tobySolutions** [comment]
I think I can handle this @FrancescoXX. Let me give it a try.

**Comment by tobySolutions** [comment]
Fixed by #383
