### ISSUE TITLE
[Feat]: remove the docusaurus references on the website 

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#382]
### Description

![image](https://user-images.githubusercontent.com/18360871/216134824-d945525c-040f-45d0-8ceb-030ec687d8df.png)

remove these images from the main page

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by tobySolutions** [comment]
Hey @FrancescoXX!! Thanks for the issue; really appreciate this. What images do you suggest we replace the images currently on the site, with?

Or should we just do away with the images altogether?
