### ISSUE TITLE
[Bug]: Text contrast to background Is off.

### ISSUE THREAD

**Issue by Jonnie-Dev** [FrancescoXX/free-Web3-resources#384]
### Description

The text on the we page doesn't have a good contrast with the background making it kinda difficult to read the text. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by tobySolutions** [comment]
Thank you so much @Jonnie-Dev!! For opening this amazing issue! You''ve set the pace here!


Do you want to work on this?

**Comment by tobySolutions** [comment]
![Screenshot from 2023-02-03 11-36-48](https://user-images.githubusercontent.com/96334363/216581409-f590db79-8736-4f79-bcd5-e24beaf15725.png)

**Comment by tobySolutions** [comment]
![Screenshot from 2023-02-03 11-42-03](https://user-images.githubusercontent.com/96334363/216581490-2147de3e-a960-4217-83cd-8429f720afb1.png)

**Comment by tobySolutions** [comment]
![Screenshot from 2023-02-03 11-42-03](https://user-images.githubusercontent.com/96334363/216581541-f7387f14-ec06-415b-b58a-4720f80608c1.png)

**Comment by tobySolutions** [comment]
![Screenshot from 2023-02-03 11-43-20](https://user-images.githubusercontent.com/96334363/216581600-a8631dc1-2fe6-441f-8539-17cb573d0fa1.png)

**Comment by tobySolutions** [comment]
If the background-repeat can be done in a much better way and the text colors of the topics on the sidebar can be made lighter, I think this issue should be fixed.

**Comment by Jonnie-Dev** [comment]
Yeah, sure. I'll look into this and provide my feedback
