### ISSUE TITLE
[Bug]: Div is not centered

### ISSUE THREAD

**Issue by SoumyadeepOSD** [FrancescoXX/free-Web3-resources#386]
### Description

<h3>If you go to Homepage of  "free-web3-resources"  official site, you can see the footer section(DOCS, COMMUNITY, MORE) must be in center to look good</h3>

<h2><b>This is the following issue image👇</b></h2>

![image](https://user-images.githubusercontent.com/115442240/216631383-cbd3842a-d670-4180-b1de-cc415be21876.png)

### To Reproduce

1. Go to https://www.freeweb3resources.com/
2. Scroll down to the bottom
3. You will find the issue

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by tobySolutions** [comment]
Would you like to take this on? @SoumyadeepOSD?

**Comment by SoumyadeepOSD** [comment]
> Would you like to take this on? @SoumyadeepOSD?

Yes! I can try to fix this issue

**Comment by tobySolutions** [comment]
Awesome @SoumyadeepOSD!! Thanks!

**Comment by tobySolutions** [comment]
Any updates on this @SoumyadeepOSD?? Need any help?

**Comment by SoumyadeepOSD** [comment]
> Any updates on this @SoumyadeepOSD?? Need any help?

@tobySolutions  
I found the bottom section of website on this file `docusaurus.config.js`, but did not find the section to change the CSS 

![image](https://user-images.githubusercontent.com/115442240/216924356-c333082a-d1c9-4082-ba4e-1d10adcfa04d.png)

**Comment by tobySolutions** [comment]
Hey @SoumyadeepOSD!! To alter the CSS, check out the custom.css file and write the CSS for the elements you're trying to alter. You can inspect the element on your Browser to see the class names so that you can alter them

**Comment by SoumyadeepOSD** [comment]
> Hey @SoumyadeepOSD!! To alter the CSS, check out the custom.css file and write the CSS for the elements you're trying to alter. You can inspect the element on your Browser to see the class names so that you can alter them

Hey @tobySolutions! I created a PR, check it out

**Comment by tobySolutions** [comment]
Hey @SoumyadeepOSD!! I just looked at it and I made a comment on your PR.

**Comment by tobySolutions** [comment]
Fixed by #391
