### ISSUE TITLE
[Feat]: enhance the announcement bar

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#388]
### Description

please replace the announcement bar message with something more catchy.

### Solution

might be: "Are you a Content Creator? Join the Community"

Join the Community should have the link to the 4c community

### Anything else?

![image](https://user-images.githubusercontent.com/18360871/216696716-145bf090-e7a8-430c-af10-631368cbde0e.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by tobySolutions** [comment]
Great issue @FrancescoXX!!

**Comment by tobySolutions** [comment]
Fixed by #392
