### ISSUE TITLE
[Feat]: Light Mode Improvement

### ISSUE THREAD

**Issue by SoumyadeepOSD** [FrancescoXX/free-Web3-resources#394]
## I've a suggestion about the Website background theme👇

- ### This is the recent website theme:

![image](https://user-images.githubusercontent.com/115442240/217888007-9dc2ee11-e0f5-4314-90e9-75ef9a71d6b5.png)

- ### The light mode of website should look like this to look more professional and premium:
![image](https://user-images.githubusercontent.com/115442240/217887480-562efcd8-8dab-478b-9160-58b9e463cfc1.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by tobySolutions** [comment]
Awesome job @SoumyadeepOSD!! That looks good!

**Comment by SoumyadeepOSD** [comment]
> Awesome job @SoumyadeepOSD!! That looks good!

@tobySolutions  Can I work on it?

**Comment by tobySolutions** [comment]
> > Awesome job @SoumyadeepOSD!! That looks good!
> 
> @tobySolutions Can I work on it?

Sure thing! I just assigned you Soumyadeep!

**Comment by tobySolutions** [comment]
Pleasure is all mine @SoumyadeepOSD. Feel free to raise a PR whenever you're ready.

**Comment by SoumyadeepOSD** [comment]
> Pleasure is all mine @SoumyadeepOSD. Feel free to raise a PR whenever you're ready.

Okay boss =) !!

**Comment by tobySolutions** [comment]
Thank you my boss @SoumyadeepOSD!

**Comment by tobySolutions** [comment]
Any updates? @SoumyadeepOSD

**Comment by tobySolutions** [comment]
Fixed by #397
