### ISSUE TITLE
[Bug]: Unnecessary outline around searchbar.

### ISSUE THREAD

**Issue by rohinish404** [FrancescoXX/free-Web3-resources#399]
### Description

The search modal has an unnecessary outline around the search bar both in light as well as dark mode and also it is not covering the whole search bar. This makes the ui look bad. This outline can be removed or changed to any other color. 
<img width="1415" alt="Screenshot 2023-02-18 at 4 17 05 PM" src="https://user-images.githubusercontent.com/92542124/219856391-fea7bf94-eca2-407c-91db-e6d5b3d3c035.png">
<img width="1415" alt="Screenshot 2023-02-18 at 4 17 11 PM" src="https://user-images.githubusercontent.com/92542124/219856396-e3192c4e-588a-4c6d-93c1-6f6d6b7985dd.png">

### To Reproduce

1. Go to homepage.
2. Click on search bar.
3. The modal appears.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by sharmashubam** [comment]
can i work on this?

**Comment by rohinish404** [comment]
@sharmashubam Wait for the maintainer to review this issue so u can get assigned:)

**Comment by tobySolutions** [comment]
Sure thing @sharmashubam!! 🚀🚀. It's all yours.

**Comment by sharmashubam** [comment]
i made a PR

**Comment by tobySolutions** [comment]
Resolved by issue #401.
