### ISSUE TITLE
[Bug]: changing the logo

### ISSUE THREAD

**Issue by rohinish404** [FrancescoXX/free-Web3-resources#402]
### Description

The current logo looks a bit odd so selecting a new logo which is more minimilistic.

### To Reproduce

1. Go to homepage
2. See logo

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by rohinish404** [comment]
I'll create a pr regarding this:)

**Comment by tobySolutions** [comment]
Awesome! Go for it @rohinish404!

**Comment by tobySolutions** [comment]
Fixed by #403
