### ISSUE TITLE
[Feat]: remove this section (is a link to a tweet)

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#417]
### Description

remove this section

https://www.freeweb3resources.com/docs/blockchains/blockchainArchitecture

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by devvsakib** [comment]
PR : #430
