### ISSUE TITLE
[Bug]: rename "Tutorials" to "Courses"

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#424]
### Description

rename "Tutorials" to Courses, both in the title and in the section

https://free-web3-resources-1l9i-git-fork-devvsakib-213a8d-francescoxx.vercel.app/docs/category/tutorials

![image](https://user-images.githubusercontent.com/18360871/224527775-1916f759-0db1-41f6-b332-703f316ca604.png)

### To Reproduce

go to 
https://free-web3-resources-1l9i-git-fork-devvsakib-213a8d-francescoxx.vercel.app/docs/category/tutorials

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by devvsakib** [comment]
PR: #431
