### ISSUE TITLE
[Feat]: remove the "Free Web3 Resources" text but leave the icon

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#427]
### Description

remove the "Free Web3 Resources" text on the top right, it's redundant

![image](https://user-images.githubusercontent.com/18360871/224528190-b7a9a374-6ccd-4c16-8b54-b1f25e2ec320.png)Remove

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by devvsakib** [comment]
Please assign me
