### ISSUE TITLE
[Bug]: Invalid link for "blockchains"

### ISSUE THREAD

**Issue by yash251** [FrancescoXX/free-Web3-resources#446]
### Description

When I go to the home page and click on "Blockchains" in the Beginner tab, it redirects it to a dead link "https://www.freeweb3resources.com/docs/blockchains/blockchains" (Page not found)

Solution-:
The link should be changed to "https://www.freeweb3resources.com/docs/blockchains"

### To Reproduce

1. Go to 'https://www.freeweb3resources.com/docs/blockchains/blockchains'
2. Click on 'Blockchains'
3. See the error

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by kumarankit999** [comment]
Is this issue closed or not??

**Comment by yash251** [comment]
> Is this issue closed or not??

yes. @FrancescoXX please close this issue
