### ISSUE TITLE
[UI Issue]: Box size height is too long according to the content in boxes

### ISSUE THREAD

**Issue by SK-21** [FrancescoXX/free-Web3-resources#459]
## On the homepage the box height is very long. 

> We should adjust box size according to the content in the boxes, to make the UI better for this website.

![screenshot](https://cdn.discordapp.com/attachments/1110569329541513277/1112584070564691978/Screenshot_2023-05-29_at_9.00.55_AM.png)

### To Reproduce

1. Go to the second section
2. Check the  boxes height
4. See the error

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by Calamivathan** [comment]
.listContainer_MWL6 {
    min-height: 9rem;
}
pls set .listContainer_MWL6 min-height to 9rem from 17rem

**Comment by NegativE333** [comment]
I'd like to work on this issue. Could you please assign it to me? 

Proposed Solution:
I suggest setting the max-height to 300px for the homecard component on the homepage to resolve the issue with its excessive height.

![image](https://github.com/FrancescoXX/free-Web3-resources/assets/102456428/e219caa9-2451-4de7-9987-351ec92b3e52)

**Comment by himughanakash** [comment]
Hey ! please assign this issue to me under hacktoberfest i would make it look better by arranging the box pixels.

**Comment by himughanakash** [comment]
add hacktoberfest tag while merging this pr.
