### ISSUE TITLE
[UI Issue]:  Not enough padding-y for Announcement-Bar on Mobile devices

### ISSUE THREAD

**Issue by nikhil1610** [FrancescoXX/free-Web3-resources#465]
### Description

On mobile devices, the content in the announcement bar doesn't have enough vertical padding.

> We can add a little padding, to improve the readability

![web3Nav](https://github.com/FrancescoXX/free-Web3-resources/assets/54029364/3d3590d5-2c91-4f6d-9dfb-c2ba075df042)
.

### To Reproduce

1. Go to docs/roadmap on a mobile device
2. See the announcement bar on top
3. See error

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by TusharGagal** [comment]
I will do this task.
