### ISSUE TITLE
[ADD]: Add logos instead of text in footer section in "community" and "more" section

### ISSUE THREAD

**Issue by kaushal1717** [FrancescoXX/free-Web3-resources#491]
### Description

In the marked area of the given screenshot the links to the socials are in text instead of logos 

<img width="1403" alt="Screenshot 2023-10-27 at 7 32 07 PM" src="https://github.com/FrancescoXX/free-Web3-resources/assets/121810303/e5bddbf6-e4bc-40fc-9521-ce73fe991670">

### Solution

I want to change it to the logos instead of text so it can look better.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by Vijaykv5** [comment]
Yes we can change the text to icons.
what do you think @FrancescoXX ?

**Comment by FrancescoXX** [comment]
@Vijaykv5 fo now it's ok,
