### ISSUE TITLE
[Bug]: Icons in course section are too big

### ISSUE THREAD

**Issue by kaushal1717** [FrancescoXX/free-Web3-resources#492]
### Description

In the courses section, the icons of Discord, Twitter and GitHub's logos are too big, if we make them smaller it will look good.

### To Reproduce

1. Go to 'Courses'
2. Click on any course
3. Scroll down to the links of socials
<img width="568" alt="image" src="https://github.com/FrancescoXX/free-Web3-resources/assets/121810303/d7591a2c-96d1-4807-af82-fd6c0558810a">

### Anything else?

@FrancescoXX please assign this issue to me so I can work on it

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by AnuragNishad12** [comment]
I solve this see this PR #495
