### ISSUE TITLE
Solana resources

### ISSUE THREAD

**Issue by rishiyadav1923** [FrancescoXX/free-Web3-resources#5]
https://dev.to/edge-and-node/The-complete-guide-to-full-stack-solana-development-with-react-anchor-rust-and-phantom-3291

**Comment by FrancescoXX** [comment]
Hi @rishiyadav1923 , is this a suggestion to include this article?

**Comment by FahimFBA** [comment]
> https://dev.to/edge-and-node/The-complete-guide-to-full-stack-solana-development-with-react-anchor-rust-and-phantom-3291

This page doesn't exist anymore, @rishiyadav1923.

**Comment by FrancescoXX** [comment]
the link doesn't work.
