### ISSUE TITLE
For now, I don't see the community (like a discord or Slack channel)

### ISSUE THREAD

**Issue by ajl388** [FrancescoXX/free-Web3-resources#54]
For now, I don't see the community (like a discord or Slack channel)
https://discord.gg/UQayXxzazc

Discord is in the platform looks like to prevent bots and spam

Please revert the Buildspace link
I will

_Originally posted by @FrancescoXX in https://github.com/FrancescoXX/free-Web3-resources/issues/52#issuecomment-1126223156_

**Comment by doctorresidual** [comment]
Thanks for raising this concern. It solves what I intended too.

**Comment by FrancescoXX** [comment]
let's discuss this in the GitHub discussions
