### ISSUE TITLE
Add latest Patrick Collins video on freecodecamp

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ewainy** [comment]
> Hello @FrancescoXX I would like to work on this issue, under which section do I have to insert the link?

@nirban256 my apologies, I created a PR before Francesco created this issue. If Francesco is happy with the structure and approves, perhaps we can work on finding some similar resources together? :)

**Comment by nirban256** [comment]
@ewainy yeah sure I'd be happy to do that

**Comment by FrancescoXX** [comment]
done by https://github.com/FrancescoXX/free-Web3-resources/commit/7c40f1f1d2ec897f134570453e77d358ccaac534
