### ISSUE TITLE
Add Learning Platform Section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#64]
Add another section for "Learning Platforms" at the end of the Readme.md file

The title should be formatted using: 

"## Learning Platforms"

**Comment by JayrajSingh65** [comment]
> I would like to work on this issue. Just need to know one thing; I will provide links to the platforms. Do I also need to include a short description for each?

hey bro i added youtube section

**Comment by JayrajSingh65** [comment]
> Add another section for "Learning Platforms" at the end of the Readme.md file
> 
> The title should be formatted using:
> 
> "## Learning Platforms"

I added yt section check it out and approve my pull request

**Comment by yash251** [comment]
Can you assign this to me ?

**Comment by JayrajSingh65** [comment]
Check out my pull request

**Comment by ewainy** [comment]
> I would like to work on this issue. Just need to know one thing; I will provide links to the platforms. Do I also need to include a short description for each?

@snehashish-ghosh98 yes please include a short description for each. Are you happy to be assigned?

**Comment by ewainy** [comment]
> Can you assign this to me @FrancescoXX ?

Hi @yash251, @snehashish-ghosh98 was first to request so the issue will be offered to them first. If @snehashish-ghosh98 comments on the resources they will add, you could make a separate PR for other resources :)

**Comment by snehashish-ghosh98** [comment]
Yes @ewainy , I will take up the issue. Thank You.

**Comment by FrancescoXX** [comment]
we have a learning platform section now. well done
