### ISSUE TITLE
Inclusion of the URL of the authors

### ISSUE THREAD

**Issue by FahimFBA** [FrancescoXX/free-Web3-resources#7]
If we can add the relevant URLs for the author, like the Twitter handle or so on, then wouldn't it be great? Please let me know what do you think about it.

**Comment by FrancescoXX** [comment]
Hi Fahim. what do you mean by Author? for the articles? Yes that's a plan. for now, I just put some basic resources, but thank you for the collaborations

**Comment by FahimFBA** [comment]
Yes, you are absolutely right! I think I should clarify that in detail though. I thought if the authors' Twitter handle or some relevant URLs got added in the article, then it would also be helpful for the audiences if they want to find out more about them.

**Comment by FrancescoXX** [comment]
I agree. let's give them credit

**Comment by FahimFBA** [comment]
Can I add some with PR?

**Comment by FrancescoXX** [comment]
sure go on

**Comment by krshdev** [comment]
I think we should appreciate contributors by adding an image of the avatars like how all projects do... Crediting the author would add tok much Noise IMO

**Comment by FahimFBA** [comment]
> I think we should appreciate contributors by adding an image of the avatars like how all projects do... Crediting the author would add too much Noise IMO

I don't think so. The authors should be credited for their awesome work. If we get too many contributors, then a whole bunch of avatars might seem overkill.
