### ISSUE TITLE
Sections restructuring

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#72]
The current links can be organized in a better way

**Solution:**
A roadmap-style list from beginner to advanced

**Comment by yash251** [comment]
Would love to work on this. Please assign it to me.

**Comment by FrancescoXX** [comment]
done @yash251

**Comment by issa-me-sush** [comment]
hey! seems fun to work on! could I please be assigned to this issue ?

**Comment by yash251** [comment]
Currently working on it @issa-me-sush

**Comment by sushrutmishra27** [comment]
Let me know if you need help with it!
