### ISSUE TITLE
[DOCUMENTATION] Add New YT channel

### ISSUE THREAD

**Issue by Susmita-Dey** [FrancescoXX/free-Web3-resources#74]
**Is your feature request related to a problem? Please describe.**
I want to add 1 new YT channels in the `README.md` file

**Describe the solution you'd like**
Channel links - [EatTheBlocks](https://www.youtube.com/c/EatTheBlocks)

**Describe alternatives you've considered**
Null

**Additional context**
Null

**Comment by Shukla007** [comment]
Yes you can add a new Youtube channel just create a new PR and you good to go 👍

**Comment by Susmita-Dey** [comment]
@Shukla007 
okay thanks
