### ISSUE TITLE
Add new section of Open Source Projects

### ISSUE THREAD

**Issue by Rahul-Prasad-07** [FrancescoXX/free-Web3-resources#79]
**Additional context**
There  are number Open Source Projects you can contribute to :

- [Aelf](https://github.com/AElfProject/AElf)
- [Bitcoin](https://github.com/bitcoin/bitcoin)
- [Brownie](https://github.com/eth-brownie/brownie)
- [Blockchain CLI](https://github.com/0xs34n/blockchain-cli)
- [Chainlink](https://github.com/smartcontractkit/chainlink)
- [chia-blockchain](https://github.com/Chia-Network/chia-blockchain)
- [Cicero](https://github.com/accordproject/cicero)
- [Corda](https://github.com/corda/corda)
- [Cosmos](https://github.com/cosmos)
- [create-web3-dapp](https://github.com/Eversmile12/create-web3-dapp)
- [Diem](https://github.com/diem/diem)
- [EIPs](https://github.com/ethereum/EIPs)
- [Embark](https://github.com/embarklabs/embark)
- [Enterprise Ethereum Alliance](https://github.com/EntEthAlliance)
- [ethers.js](https://github.com/ethers-io/ethers.js)
- [fabric](https://github.com/hyperledger/fabric)
- [Foundry](https://github.com/foundry-rs/foundry)
- [Ganache UI](https://github.com/trufflesuite/ganache-ui)
- [go-ethereum](https://github.com/ethereum/go-ethereum)
- [Hardhat](https://github.com/NomicFoundation/hardhat)
- [Holochain](https://github.com/holochain)
- [Hyperledger](https://github.com/hyperledger/)
- [ipfs](https://github.com/ipfs/ipfs)
- [LBRY](https://github.com/lbryio/lbry-desktop)
- [Lisk](https://github.com/LiskHQ)
- [Metamask](https://github.com/MetaMask)
- [Monero](https://github.com/monero-project/monero)
- [Neo](https://github.com/neo-project/neo)
- [Openchain](https://github.com/openchain)
- [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts)
- [Quorum](https://github.com/ConsenSys/quorum)
- [RemixProject](https://github.com/ethereum/remix-project)
- [Solana](https://github.com/solana-labs/solana)
- [Solidity](https://github.com/ethereum/solidity)
- [truffle](https://github.com/trufflesuite/truffle)
- [Wallet](https://github.com/DemocracyEarth/wallet)
- [Web3j](https://github.com/web3j/web3j)
- [Web3Swift](https://github.com/skywinder/web3swift)
- [web3.swift](https://github.com/Boilertalk/Web3.swift)
- [web3.js](https://github.com/ChainSafe/web3.js)
- [web3.php](https://github.com/web3p/web3.php)
- [web3.py](https://github.com/ethereum/web3.py)
- [XuperChain](https://github.com/xuperchain/xuperchain)
- [Zilliqa](https://github.com/Zilliqa/Zilliqa)
-

**Comment by Rahul-Prasad-07** [comment]
I want to add some open source projects that are available for us to contribute. I hope this will help our community.

**Comment by dmdbilal** [comment]
is this issue still open?
