### ISSUE TITLE
Add dark mode to the website

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#86]
Please add the dark mode functionality 

The light mode should still be available

Optional: set dark mode as the default

Current website link
https://francescoxx.github.io/free-Web3-resources/#/

**Comment by mhammadsaani** [comment]
I can work on this!

**Comment by vaibhav-zemo** [comment]
I am willing to work on this if on one is assigned

**Comment by sushantgwr87** [comment]
Dark Mode integration using button on right top with a good contrasting theme. It can be set by default as well. Please assign me so that I can start the work. Thank You.

**Comment by Rupesh-Darimisetti** [comment]
Hello francesso i cannot find the body with the content available in website how can I get that one to add functionality for modification of theme

**Comment by sushantgwr87** [comment]
I am willing to work on this Project. Idea is to add button at top right of the page to switch themes. As you are using Docsify, I will use their default themes of dark and vue.

Kindly assign me to start working on this.

**Comment by yash251** [comment]
Please assign it to me @FrancescoXX

**Comment by A1965** [comment]
Hii @FrancescoXX , I can add it, so please can you assign this to me.
Thankyou
