### ISSUE TITLE
Add a in-person presentations section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#88]
Add a section for Presentations

## In-person Presentations

**Comment by Johnnyteck** [comment]
This can go before the youtube channels section right. Would love to give it a go

**Comment by FrancescoXX** [comment]
go for it

**Comment by Johnnyteck** [comment]
D you have links to the sessions so I can add or I just add the header

**Comment by FrancescoXX** [comment]
just create the section for now
