### ISSUE TITLE
I think this would work

### ISSUE THREAD

**Issue by rishiyadav1923** [FrancescoXX/free-Web3-resources#9]
https://dev.to/edge-and-node/the-complete-guide-to-full-stack-solana-development-with-react-anchor-rust-and-phantom-3291

**Comment by FrancescoXX** [comment]
Hi, is this a suggestion to include this?

**Comment by FrancescoXX** [comment]
Nice suggestion, we need to fix this issue before #28

**Comment by FrancescoXX** [comment]
added by https://github.com/FrancescoXX/free-Web3-resources/commit/0f9b6c9794723bee24da90e1eac10d389c5a2e23
