### ISSUE TITLE
Broken links in Contributing.md

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#90]
**Describe the bug**
There are 21 broken links in Contributing.md

**To Reproduce**
1. https://github.com/FrancescoXX/free-Web3-resources/blob/main/CONTRIBUTING.md
2. Click on "Beginner issues" or "Help wanted" link
4. the github 404 page is displayed

**Expected behavior**
links should redirect to good-first issue and help wanted issues

**Screenshots**
![image](https://user-images.githubusercontent.com/18360871/193400267-777503bd-6d49-41f6-8baa-2cb91a79382d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 

**Additional context**
links should be:
- https://github.com/FrancescoXX/free-Web3-resources/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
- https://github.com/FrancescoXX/free-Web3-resources/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by mhammadsaani** [comment]
I want to work on this

**Comment by hridaya423** [comment]
I can work on this!

**Comment by Johnnyteck** [comment]
Can you assign me this please

**Comment by clairecharles** [comment]
can i work on this?

**Comment by mhammadsaani** [comment]
@clairecharles This has been merged!

**Comment by FrancescoXX** [comment]
well done
